  server:
    port: 9000

  spring:
    servlet:
      multipart:
        max-file-size: 500KB
        max-request-size: 500KB
    data:
      mongodb:
        host: ${DB_HOST}
        port: ${DB_PORT}
        database: ${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASS}
